import { DataState } from '../types/index';

export const initialState: DataState = {
  projects: [],
  programs: [],
  resources: [],
  resourceRequests: [],
  risks: [],
  issues: [],
  budgetItems: [],
  expenses: [],
  changeOrders: [],
  purchaseOrders: [],
  qualityReports: [],
  nonConformanceReports: [],
  communicationLogs: [],
  stakeholders: [],
  documents: [],
  activityCodes: [],
  userDefinedFields: [],
  fundingSources: [],
  calendars: [],
  users: [],
  roles: [],
  eps: [
      { id: 'EPS-ROOT', parentId: null, name: 'Enterprise Root', code: 'ROOT' }
  ],
  obs: [
      { id: 'OBS-ROOT', parentId: null, name: 'Executive Hierarchy' }
  ],
  locations: [],
  workflows: [],
  dataJobs: [],
  integrations: [],
  extensions: [],
  expenseCategories: [],
  issueCodes: [],
  costBook: [],
  standardTemplates: [],
  governance: {
      alerts: [],
      auditLog: [],
      exchangeRates: { 'USD': 1.0 },
      inflationRate: 0.03,
      riskTolerance: 'Moderate',
      strategicWeights: { 'financial': 0.4, 'strategic': 0.4, 'risk': 0.2 },
      vendorBlacklist: [],
      scoringCriteria: [
          { id: 'strategic', name: 'Strategic Alignment', weight: 0.4, description: 'Direct contribution to corporate goals.' },
          { id: 'financial', name: 'NPV / ROI', weight: 0.3, description: 'Projected financial return.' },
          { id: 'risk', name: 'Risk Profile', weight: 0.2, description: 'Inherent execution uncertainty.' },
          { id: 'feasibility', name: 'Resource Availability', weight: 0.1, description: 'Ability to staff without conflict.' }
      ],
      scheduling: {
          retainedLogic: true,
          calculateCriticalPathUsing: 'Longest Path',
          computeMultipleFloatPaths: false,
          floatPathTaskCount: 0,
          autoSaveOnSchedule: true,
          defaultTaskType: 'Fixed Duration'
      },
      resourceDefaults: {
          defaultWorkHoursPerDay: 8,
          autoLevelingThreshold: 100,
          usePricePerUnitForCost: true,
          allowOvertimeInPlanning: false
      },
      security: {
          mfa: true,
          passwordComplexity: 'High',
          sessionLimit: 30,
          ipLock: false,
          allowedIps: [],
          allowPublicLinks: false,
          enforceHttps: true,
          loginRetries: 5
      },
      organization: {
          name: 'Nexus Deployment',
          shortName: 'NEX',
          taxId: '',
          fiscalYearStart: 'January',
          timezone: 'UTC',
          language: 'English (US)',
          currency: 'USD'
      },
      notificationPreferences: [],
      billing: {
          licenseType: 'Enterprise',
          renewalDate: '',
          seatLimit: 10,
          storageLimitGB: 100,
          history: []
      }
  },
  strategicGoals: [],
  strategicDrivers: [],
  portfolioScenarios: [],
  governanceDecisions: [],
  esgMetrics: [],
  portfolioRisks: [],
  programObjectives: [],
  programOutcomes: [],
  programDependencies: [],
  programChangeRequests: [],
  programRisks: [],
  programIssues: [],
  programStakeholders: [],
  programCommunicationPlan: [],
  programAllocations: [],
  programFundingGates: [],
  programStageGates: [],
  programTransitionItems: [],
  integratedChanges: [],
  governanceRoles: [],
  governanceEvents: [],
  programQualityStandards: [],
  programAssuranceReviews: [],
  programArchitectureStandards: [],
  programArchitectureReviews: [],
  tradeoffScenarios: [],
  contracts: [],
  solicitations: [],
  procurementPlans: [],
  procurementPackages: [],
  supplierReviews: [],
  claims: [],
  makeOrBuyAnalysis: [],
  globalChangeRules: [],
  invoices: [],
  timesheets: [],
  skills: [],
  benefits: [],
  rbs: [],
  vendors: [],
  qualityStandards: [],
  unifier: {
      definitions: [],
      records: [],
      costSheet: {
          columns: [],
          rows: []
      },
      cashFlowCurves: [],
      fundAllocations: []
  },
  dailyLogs: [],
  safetyIncidents: [],
  punchList: [],
  roadmapLanes: [],
  roadmapItems: [],
  kanbanTasks: [],
  portfolioCommunicationPlan: [],
  materialReceipts: [],
  activities: [],
  teamEvents: [],
  pipelineStages: [],
  knowledgeBase: [],
  etlMappings: [],
  costReports: [],
  costMeetings: [],
  costAlerts: [],
  reportDefinitions: [],
  systemMonitoring: {
      metrics: [],
      services: [],
      throughput: []
  },
  staging: {
      activeImportId: null,
      entityType: 'Project',
      records: [],
      isProcessing: false,
      summary: { total: 0, valid: 0, error: 0 }
  },
  extensionData: {
      financial: { allocation: [], cashFlow: [], regulatoryAudits: [], initiatives: [] },
      construction: { submittals: [] },
      government: { fundsFlow: [], fiscalYears: [], appropriations: [], treasuryStats: [], acquisitionPrograms: [], defenseStats: { readiness: 'N/A', personnel: 'N/A', budget: 'N/A', cyberStatus: 'Unknown', logisticsStatus: 'Unknown' }, energyStats: { gridLoad: 'N/A', capacity: 'N/A', reserve: 'N/A', renewablePercent: 0, renewableTarget: 0, mix: [] } },
      dod: { milestones: [], phases: [], evmsData: [], quadChart: { performance: [], schedule: [], cost: [], technical: [] } },
      erpTransactions: [],
      bim: { tree: [] },
      gis: { features: [] }
  }
};