
import { DataState } from '../types/index';

// This is the "Day Zero" state of the application.
// All data is initialized as empty to ensure no mock or static data leaks into production.
// The application is designed to be populated from a dynamic data source (e.g., API, local DB).

export const initialState: DataState = {
  projects: [],
  programs: [],
  resources: [],
  resourceRequests: [],
  risks: [],
  issues: [],
  budgetItems: [],
  expenses: [],
  changeOrders: [],
  purchaseOrders: [],
  qualityReports: [],
  nonConformanceReports: [],
  communicationLogs: [],
  stakeholders: [],
  documents: [],
  activityCodes: [],
  userDefinedFields: [],
  fundingSources: [],
  calendars: [],
  users: [],
  roles: [],
  eps: [],
  obs: [],
  locations: [],
  workflows: [],
  dataJobs: [],
  integrations: [],
  extensions: [],
  expenseCategories: [],
  issueCodes: [],
  costBook: [],
  standardTemplates: [],
  governance: {
      alerts: [],
      auditLog: [],
      exchangeRates: { 'USD': 1.0 },
      inflationRate: 0.03,
      riskTolerance: 'Moderate',
      strategicWeights: {},
      vendorBlacklist: [],
      scoringCriteria: [],
      scheduling: {
          retainedLogic: true,
          calculateCriticalPathUsing: 'Longest Path',
          computeMultipleFloatPaths: false,
          floatPathTaskCount: 0,
          autoSaveOnSchedule: true,
          defaultTaskType: 'Fixed Duration'
      },
      resourceDefaults: {
          defaultWorkHoursPerDay: 8,
          autoLevelingThreshold: 100,
          usePricePerUnitForCost: true,
          allowOvertimeInPlanning: false
      },
      security: {
          mfa: true,
          passwordComplexity: 'High',
          sessionLimit: 30,
          ipLock: false,
          allowedIps: [],
          allowPublicLinks: false,
          enforceHttps: true,
          loginRetries: 5
      },
      organization: {
          name: 'Nexus PPM',
          shortName: 'NEXUS',
          taxId: '',
          fiscalYearStart: 'January',
          timezone: 'UTC -5 (Eastern Time)',
          language: 'English (US)',
          currency: 'USD'
      },
      notificationPreferences: [],
      billing: {
          licenseType: 'Enterprise',
          renewalDate: '',
          seatLimit: 0,
          storageLimitGB: 0,
          history: []
      }
  },
  strategicGoals: [],
  strategicDrivers: [],
  portfolioScenarios: [],
  governanceDecisions: [],
  esgMetrics: [],
  portfolioRisks: [],
  programObjectives: [],
  programOutcomes: [],
  programDependencies: [],
  programChangeRequests: [],
  programRisks: [],
  programIssues: [],
  programStakeholders: [],
  programCommunicationPlan: [],
  programAllocations: [],
  programFundingGates: [],
  programStageGates: [],
  programTransitionItems: [],
  integratedChanges: [],
  governanceRoles: [],
  governanceEvents: [],
  programQualityStandards: [],
  programAssuranceReviews: [],
  programArchitectureStandards: [],
  programArchitectureReviews: [],
  tradeoffScenarios: [],
  contracts: [],
  solicitations: [],
  procurementPlans: [],
  procurementPackages: [],
  supplierReviews: [],
  claims: [],
  makeOrBuyAnalysis: [],
  globalChangeRules: [],
  invoices: [],
  timesheets: [],
  skills: [],
  benefits: [],
  rbs: [],
  vendors: [],
  qualityStandards: [],
  unifier: {
      definitions: [],
      records: [],
      costSheet: {
          columns: [],
          rows: []
      },
      cashFlowCurves: [],
      fundAllocations: []
  },
  dailyLogs: [],
  safetyIncidents: [],
  punchList: [],
  roadmapLanes: [],
  roadmapItems: [],
  kanbanTasks: [],
  portfolioCommunicationPlan: [],
  materialReceipts: [],
  activities: [],
  teamEvents: [],
  pipelineStages: [],
  knowledgeBase: [
      { 
          id: 'KB-001', 
          title: 'Budget Transfer Policy', 
          category: 'Finance', 
          content: '<h3>Overview</h3><p>All transfers above $10k require PMO approval...</p>',
          authorId: 'U-001',
          lastUpdated: '2024-05-15',
          views: 42,
          tags: ['Compliance', 'Finance']
      }
  ],
  etlMappings: [],
  costReports: [],
  costMeetings: [],
  costAlerts: [],
  reportDefinitions: [
      { id: 'status_summary', title: 'Monthly Status Report', category: 'General', description: 'High-level executive summary of project health, schedule, and key issues.', icon: 'FileText', type: 'Standard' },
      { id: 'cost_ledger', title: 'Cost Ledger Detail', category: 'Financial', description: 'Detailed transaction log of all budget changes, commitments, and actuals.', icon: 'Table', type: 'Standard' },
      { id: 'risk_register', title: 'Risk Register Export', category: 'Risk', description: 'Comprehensive list of active risks, scores, and mitigation plans.', icon: 'AlertTriangle', type: 'Standard' },
      { id: 'evm_analysis', title: 'Earned Value Analysis', category: 'Performance', description: 'SPI, CPI, and EAC forecasting metrics by WBS.', icon: 'TrendingUp', type: 'Standard' },
      { id: 'resource_load', title: 'Resource Utilization', category: 'Resource', description: 'Staffing demand vs capacity heatmaps.', icon: 'Activity', type: 'Standard' },
  ],
  systemMonitoring: {
      metrics: [
          { id: 'm-db-size', name: 'Database Size', value: 0.0, unit: 'MB', threshold: 500, trend: [] },
          { id: 'm-schema', name: 'Schema Version', value: 1.3, unit: 'v', threshold: 2.0, trend: [] },
          { id: 'm-backup', name: 'Last Backup', value: 0, unit: 'mins ago', threshold: 60, trend: [] }
      ],
      services: [],
      throughput: []
  },
  staging: {
      activeImportId: null,
      entityType: 'Project',
      records: [],
      isProcessing: false,
      summary: { total: 0, valid: 0, error: 0 }
  },
  extensionData: {
      financial: { allocation: [], cashFlow: [], regulatoryAudits: [], initiatives: [] },
      construction: { submittals: [] },
      government: { fundsFlow: [], fiscalYears: [], appropriations: [], treasuryStats: [], acquisitionPrograms: [], defenseStats: { readiness: 'N/A', personnel: 'N/A', budget: 'N/A', cyberStatus: 'Unknown', logisticsStatus: 'Unknown' }, energyStats: { gridLoad: 'N/A', capacity: 'N/A', reserve: 'N/A', renewablePercent: 0, renewableTarget: 0, mix: [] } },
      dod: { milestones: [], phases: [], evmsData: [], quadChart: { performance: [], schedule: [], cost: [], technical: [] } },
      erpTransactions: [],
      bim: { tree: [] },
      gis: { features: [] }
  }
};
